name: Update Repo and Merge

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        repository: tfugbbsr/tfugbbsr.github.io
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Change remote repository URL
      run: |
        git remote set-url origin https://github.com/tfug-bbsr/tfugbbsr.github.io.git

    - name: Pull the latest changes
      run: |
        git pull origin main --rebase

    - name: Push changes to new repository
      run: |
        git push origin main

    - name: Merge automatically
      run: |
        git fetch origin main
        git merge --no-ff -m "Automated merge after repository update"
        git push origin main
